// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Person struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Age       int32   `json:"age"`
	Gender    bool    `json:"gender"`
	Email     string  `json:"email"`
	Phone     *string `json:"phone,omitempty"`
	IsActive  bool    `json:"isActive"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type PersonInput struct {
	Name      string  `json:"name"`
	Age       int32   `json:"age"`
	Gender    bool    `json:"gender"`
	Email     string  `json:"email"`
	Phone     *string `json:"phone,omitempty"`
	IsActive  bool    `json:"isActive"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
